### PR TITLE
snapshot 0.7.0 the sentinel update

### PR DESCRIPTION
**Pull request by ham1255**

### CODE REVIEW

**Comment by licen150** [comment]
image
Litebans

**Comment by licen150** [comment]
Bug with Litebans not fixed

**Comment by ham1255** [comment]
> Bug with Litebans not fixed

did you try latest build from https://github.com/Limework/RedisBungee/actions

**Comment by licen150** [comment]
Yes, i tried latest build

**Comment by ham1255** [comment]
> Yes, i tried latest build

Please open a issue

**Comment by ham1255** [comment]
this wont be merged anymore.

**Pull request closed without merging**
